SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[DMX_ExtractConcatenate]
 (@EntryId INT, @SEPARATOR NVARCHAR(8))
RETURNS NVARCHAR(2000)
AS
BEGIN
 DECLARE @RES NVARCHAR(2000)
 SELECT @RES = (SELECT ISNULL(Extract,'') AS X
  FROM dbo.DMX_SearchResults
  WHERE EntryId=@EntryId
  FOR XML PATH(''));
 SET @RES = REPLACE(@RES, '</X><X>', @SEPARATOR);
 SET @RES = REPLACE(@RES, '<X>', '');
 SET @RES = REPLACE(@RES, '</X>', '');
 RETURN @RES
END
GO
