SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/*** EventsSignupsSave ***/
CREATE PROCEDURE [dbo].[EventsSignupsSave]
(
    @EventID int, 
    @SignupID int, 
    @ModuleID int, 
    @UserID int,
    @Approved int,
    @PayPalStatus nvarchar(50), 
    @PayPalReason nvarchar(100), 
    @PayPalTransID nvarchar(50), 
    @PayPalPayerID nvarchar(50), 
    @PayPalPayerStatus nvarchar(50), 
    @PayPalRecieverEmail nvarchar(100), 
    @PayPalUserEmail nvarchar(100), 
    @PayPalPayerEmail nvarchar(100), 
    @PayPalFirstName nvarchar(50), 
    @PayPalLastName nvarchar(50), 
    @PayPalAddress nvarchar(100), 
    @PayPalCity nvarchar(25), 
    @PayPalState nvarchar(25), 
    @PayPalZip nvarchar(25), 
    @PayPalCountry nvarchar(25), 
    @PayPalCurrency nvarchar(25), 
    @PayPalPaymentDate datetime , 
    @PayPalAmount money, 
    @PayPalFee money,
    @NoEnrolees int,
    @AnonEmail nvarchar(256),
    @AnonName nvarchar(128),
    @AnonTelephone nvarchar(50),
    @AnonCulture nvarchar(10),
    @AnonTimeZoneId nvarchar(100),
	@FirstName nvarchar(50),
	@LastName nvarchar(50),
	@Company nvarchar(50),
	@JobTitle nvarchar(50),
	@ReferenceNumber nvarchar(50),
	@Street nvarchar(50),
	@PostalCode nvarchar(50),
	@City nvarchar(50),
	@Region nvarchar(50),
	@Country nvarchar(50)
)
AS
BEGIN
SET NOCOUNT ON;
SET DATEFORMAT mdy;

IF @SignupID = 0 OR @SignupID IS NULL
    INSERT dbo.[EventsSignups]
    (
        EventID,
        ModuleID,
        UserID,
        Approved,
        PayPalStatus, 
        PayPalReason, 
        PayPalTransID, 
        PayPalPayerID, 
        PayPalPayerStatus, 
        PayPalRecieverEmail, 
        PayPalUserEmail,
        PayPalPayerEmail, 
        PayPalFirstName, 
        PayPalLastName, 
        PayPalAddress, 
        PayPalCity, 
        PayPalState, 
        PayPalZip, 
        PayPalCountry, 
        PayPalCurrency, 
        PayPalPaymentDate, 
        PayPalAmount, 
        PayPalFee,
        NoEnrolees,
        AnonEmail,
        AnonName,
        AnonTelephone,
        AnonCulture,
		FirstName,
		LastName,
		Company,
		JobTitle,
		ReferenceNumber,
		Street,
		PostalCode,
		City,
		Region,
		Country
    )
    VALUES
    (
        @EventID,
        @ModuleID,
        @UserID,
        @Approved,
        @PayPalStatus, 
        @PayPalReason, 
        @PayPalTransID, 
        @PayPalPayerID, 
        @PayPalPayerStatus, 
        @PayPalRecieverEmail, 
        @PayPalUserEmail,
        @PayPalPayerEmail, 
        @PayPalFirstName, 
        @PayPalLastName, 
        @PayPalAddress, 
        @PayPalCity, 
        @PayPalState, 
        @PayPalZip, 
        @PayPalCountry, 
        @PayPalCurrency, 
        @PayPalPaymentDate, 
        @PayPalAmount, 
        @PayPalFee,
        @NoEnrolees,
        @AnonEmail,
        @AnonName,
        @AnonTelephone,
        @AnonCulture,
		@FirstName,
		@LastName,
		@Company,
		@JobTitle,
		@ReferenceNumber,
		@Street,
		@PostalCode,
		@City,
		@Region,
		@Country
    )
ELSE
    UPDATE dbo.[EventsSignups] SET
        EventID = @EventID,
        UserID = @UserID,
        Approved = @Approved,
        PayPalStatus = @PayPalStatus, 
        PayPalReason = @PayPalReason, 
        PayPalTransID = @PayPalTransID, 
        PayPalPayerID = @PayPalPayerID, 
        PayPalPayerStatus = @PayPalPayerStatus, 
        PayPalRecieverEmail = @PayPalRecieverEmail, 
        PayPalUserEmail = @PayPalUserEmail,
        PayPalPayerEmail = @PayPalPayerEmail, 
        PayPalFirstName = @PayPalFirstName, 
        PayPalLastName = @PayPalLastName, 
        PayPalAddress = @PayPalAddress, 
        PayPalCity = @PayPalCity, 
        PayPalState = @PayPalState, 
        PayPalZip = @PayPalZip, 
        PayPalCountry = @PayPalCountry, 
        PayPalCurrency = @PayPalCurrency, 
        PayPalPaymentDate = @PayPalPaymentDate, 
        PayPalAmount = @PayPalAmount, 
        PayPalFee = @PayPalFee,
        NoEnrolees = @NoEnrolees,
        AnonEmail = @AnonEmail,
        AnonName = @AnonName,
        AnonTelephone = @AnonTelephone,
        AnonCulture = @AnonCulture,
        AnonTimeZoneId = @AnonTimeZoneId,
		FirstName = @FirstName,
		LastName = @LastName,
		Company = @Company,
		JobTitle = @JobTitle,
		ReferenceNumber = @ReferenceNumber,
		Street = @Street,
		PostalCode = @PostalCode,
		City = @City,
		Region = @Region,
		Country = @Country
    WHERE	SignupID = @SignupID
		AND	ModuleID = @ModuleID

SELECT	s.EventID,
		s.SignupID,
		s.ModuleID,
		s.Userid,
		s.Approved,
		u.DisplayName as UserName,
		u.Email,
		c.EventTimeBegin,
		c.Duration,
		c.EventName,
		c.Importance,
		c.Approved as EventApproved,
		c.MaxEnrollment,
		(	SELECT SUM(NoEnrolees)
			FROM dbo.[EventsSignups]
			WHERE EventID = c.EventID AND c.Signups = 1
		) as Enrolled,
        PayPalStatus, 
        PayPalReason, 
        PayPalTransID, 
        PayPalPayerID, 
        PayPalPayerStatus, 
        PayPalRecieverEmail, 
        PayPalUserEmail,
        PayPalPayerEmail, 
        PayPalFirstName, 
        PayPalLastName, 
        PayPalAddress, 
        PayPalCity, 
        PayPalState, 
        PayPalZip, 
        PayPalCountry, 
        PayPalCurrency, 
        PayPalPaymentDate, 
        PayPalAmount, 
        PayPalFee,
        NoEnrolees,
        r.EventTimeZoneId,
        AnonEmail,
        AnonName,
        AnonTelephone,
        AnonCulture,
        AnonTimeZoneId,
		S.FirstName,
		S.LastName,
		S.Company,
		S.JobTitle,
		S.ReferenceNumber,
		S.Street,
		S.PostalCode,
		S.City,
		S.Region,
		S.Country
FROM dbo.[EventsRecurMaster] AS r RIGHT OUTER JOIN
     dbo.[Events] AS c ON r.RecurMasterID = c.RecurMasterID RIGHT OUTER JOIN
     dbo.[EventsSignups] AS s LEFT OUTER JOIN
     dbo.[Users] AS u ON s.UserID = u.UserID ON c.EventID = s.EventID
Where  s.SignupID = scope_identity()
ORDER BY c.EventTimeBegin, c.EventName, UserName
END
GO
